Implement container to wrap all content
TN4HPEL3/vinissimo pull request #12
Opened 2024-04-14 07:39 UTC by TN4HPEL3

2024-04-15 13:10 UTC, AnnaIstochnikova requested changes

2024-04-15 13:10 UTC, AnnaIstochnikova commented on src/components/templates/Container/Container.module.css
Can we use rem instead of px?

2024-04-29 10:09 UTC, AnnaIstochnikova approved these changes

2024-04-29 10:11 UTC, merged

2024-05-07 06:53 UTC, TN4HPEL3 reviewed
Ready to merge ✅

2024-05-07 06:53 UTC, TN4HPEL3 commented on src/components/templates/Container/Container.module.css
@AnnaIstochnikova nicely done 💪