Implement header navigation
TN4HPEL3/vinissimo pull request #6
Opened 2024-04-11 20:25 UTC by TN4HPEL3

2024-04-12 06:42 UTC, AnnaIstochnikova commented on src/components/organisms/NavigationListOrganisms/NavigationListOrganisms.jsx
Shouldn't it be the <nav> tag instead of the <ul>?

2024-04-15 13:08 UTC, AnnaIstochnikova requested changes

2024-04-15 13:08 UTC, AnnaIstochnikova commented on src/components/organisms/NavigationListOrganisms/NavigationListOrganisms.jsx
Shouldn't it be the nav tag instead of the ul?

2024-04-29 09:48 UTC, AnnaIstochnikova approved these changes

2024-04-29 09:52 UTC, AnnaIstochnikova requested changes
Are you sure we want to merge this branch into 'main' instead of 'dev'?

2024-05-07 06:26 UTC, TN4HPEL3 commented
> Are you sure we want to merge this branch into 'main' instead of 'dev'?

😅

2024-05-07 06:43 UTC, TN4HPEL3 commented
Conflicts resolved. @AnnaIstochnikova

2024-05-07 09:18 UTC, AnnaIstochnikova approved these changes

2024-05-07 09:19 UTC, merged